;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Player AirDash 0010",NewTagName="Player.Dash.AirDash 0010")
+GameplayTagRedirects=(OldTagName="Player BackDash 0010",NewTagName="Player.Dash.BackDash 0010")
+GameplayTagRedirects=(OldTagName="Player Dash 0010",NewTagName="Player.Dash.Dash 0010")
+GameplayTagRedirects=(OldTagName="GameplayCue.UI.Update",NewTagName="GameplayCue.UI.Renew")
+GameplayTagRedirects=(OldTagName="GameplayCue.Attack.Ranged",NewTagName="GameplayCue.Attack.Glaive")
+GameplayTagList=(Tag="AI",DevComment="")
+GameplayTagList=(Tag="AI.Combat",DevComment="")
+GameplayTagList=(Tag="AI.Idle",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.GainMeter",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Data.Setup.SetMaxHealth",DevComment="")
+GameplayTagList=(Tag="Enemy",DevComment="")
+GameplayTagList=(Tag="Enemy.Golem.JumpSlam",DevComment="")
+GameplayTagList=(Tag="Enemy.Golem.SideSwipe",DevComment="")
+GameplayTagList=(Tag="Enemy.Golem.VerticalSlam",DevComment="")
+GameplayTagList=(Tag="Enemy.HitShake",DevComment="")
+GameplayTagList=(Tag="Enemy.Knockback",DevComment="")
+GameplayTagList=(Tag="Enemy.Melee",DevComment="")
+GameplayTagList=(Tag="Enemy.Wolf.Dodge",DevComment="")
+GameplayTagList=(Tag="Enemy.Wolf.HeavyAttack01",DevComment="")
+GameplayTagList=(Tag="Enemy.Wolf.LightAttack01",DevComment="")
+GameplayTagList=(Tag="Enemy.Wolf.RangedAttack01",DevComment="")
+GameplayTagList=(Tag="Event.GeneralPurposeMoveWindowStart",DevComment="")
+GameplayTagList=(Tag="Event.GeneralPurposeMoveWindowStop",DevComment="")
+GameplayTagList=(Tag="Event.LightAttack01CancelWindowStart",DevComment="")
+GameplayTagList=(Tag="Event.LightAttack01MoveWindowStart",DevComment="")
+GameplayTagList=(Tag="Event.LightAttack02CancelWindowStart",DevComment="")
+GameplayTagList=(Tag="Event.LightAttack02MoveWindowStart",DevComment="")
+GameplayTagList=(Tag="Event.ParryWindowEnd",DevComment="")
+GameplayTagList=(Tag="Event.ParryWindowStart",DevComment="")
+GameplayTagList=(Tag="Event.Ranged01CancelWindowStart",DevComment="")
+GameplayTagList=(Tag="Event.Ranged01MoveWindowStart",DevComment="")
+GameplayTagList=(Tag="Event.Ranged02CancelWindowStart",DevComment="")
+GameplayTagList=(Tag="Event.Ranged02MoveWindowStart",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Attack.Glaive",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Attack.OneHandedSword",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Defend.ParryingDagger",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Enemy.Wolf.DodgeAttack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Other.Hitstop",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Other.Hitstun",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Status.Death",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Status.ParryStunned",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Super.Effect",DevComment="")
+GameplayTagList=(Tag="GameplayCue.UI.Renew",DevComment="")
+GameplayTagList=(Tag="Player.Aerial.AerialHeavyAttack",DevComment="")
+GameplayTagList=(Tag="Player.Aerial.AerialLightAttack",DevComment="")
+GameplayTagList=(Tag="Player.Cancel.LightAttack01AttackCancel",DevComment="")
+GameplayTagList=(Tag="Player.Cancel.LightAttack02AttackCancel",DevComment="")
+GameplayTagList=(Tag="Player.Cancel.Ranged01AttackCancel",DevComment="")
+GameplayTagList=(Tag="Player.Cancel.Ranged02AttackCancel",DevComment="")
+GameplayTagList=(Tag="Player.Dash.AirDash 0010",DevComment="")
+GameplayTagList=(Tag="Player.Dash.BackDash 0010",DevComment="")
+GameplayTagList=(Tag="Player.Dash.Dash 0010",DevComment="")
+GameplayTagList=(Tag="Player.Death",DevComment="")
+GameplayTagList=(Tag="Player.HeavyAttack.HeavyAttack01",DevComment="")
+GameplayTagList=(Tag="Player.IFrames",DevComment="")
+GameplayTagList=(Tag="Player.Knockback",DevComment="")
+GameplayTagList=(Tag="Player.Knockback-Light",DevComment="")
+GameplayTagList=(Tag="Player.LightAttack.LightAttack01",DevComment="")
+GameplayTagList=(Tag="Player.LightAttack.LightAttack02",DevComment="")
+GameplayTagList=(Tag="Player.LightAttack.LightAttack03",DevComment="")
+GameplayTagList=(Tag="Player.ManaRegen.Block",DevComment="")
+GameplayTagList=(Tag="Player.Parry.Left",DevComment="")
+GameplayTagList=(Tag="Player.Parry.LeftParryActive",DevComment="")
+GameplayTagList=(Tag="Player.Parry.ParrySuccessful",DevComment="")
+GameplayTagList=(Tag="Player.Ranged.Ranged01",DevComment="")
+GameplayTagList=(Tag="Player.Ranged.Ranged02",DevComment="")
+GameplayTagList=(Tag="Player.Ranged.Ranged03",DevComment="")
+GameplayTagList=(Tag="Player.Super.Super01",DevComment="")

